# Generated by Django 6.0.3 on 2026-03-24 22:29

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('color', models.CharField(blank=True, default='4caf50', help_text='Color in HEX format', max_length=6, verbose_name='Color')),
                ('icon', models.CharField(blank=True, max_length=10, null=True, verbose_name='Emoji icon')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Balance')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('color', models.CharField(blank=True, default='4caf50', help_text='Color in HEX format', max_length=6, verbose_name='Color')),
                ('icon', models.CharField(blank=True, max_length=10, null=True, verbose_name='Emoji icon')),
                ('name', models.CharField(max_length=30, verbose_name='Category name')),
                ('category_type', models.CharField(choices=[('+', 'Income'), ('-', 'Expense')], default='-', max_length=1, verbose_name='Category type')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Name')),
                ('symbol', models.CharField(max_length=5, unique=True, verbose_name='Symbol')),
                ('abbr', models.CharField(max_length=5, unique=True, verbose_name='Abbreviation')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Amount')),
                ('account_amount', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name="Amount in account's currency")),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Exchange rate to account currency')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Description')),
                ('performed_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transfers',
            },
        ),
    ]
