# Generated by Django 6.0.3 on 2026-03-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='account',
            name='icon',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Emoji icon'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Emoji icon'),
        ),
    ]
