# Generated by Django 6.0.3 on 2026-03-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_system_reserved',
            field=models.BooleanField(default=False, verbose_name='System reserved'),
        ),
    ]
