# Generated by Django 6.0.3 on 2026-03-26 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_category_is_system_reserved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_transfer',
            field=models.BooleanField(default=False, verbose_name='Transfer'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(('is_transfer', False), ('is_system_reserved', True), _connector='OR'), name='transfer_requires_system_reserved'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('is_transfer', True)), fields=('user', 'category_type'), name='unique_transfer_per_user_and_type'),
        ),
    ]
