# Generated by Django 6.0.3 on 2026-03-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_alter_account_description_alter_account_icon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount_converted',
            new_name='account_amount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Exchange rate to account currency'),
        ),
    ]
