# Generated by Django 6.0.3 on 2026-03-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_category_is_transfer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='allow_negative',
            field=models.BooleanField(default=False, verbose_name='Allow negative'),
        ),
    ]
